version: '3'

services:
  postgres:
    container_name: fluxo_mineracao
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - .docker:/data/postgres
    ports:
      - "${DB_PORT}:5432"
volumes:
    postgres: